name: artifact_deployed

on:
  # workflow_dispatch is mandatory, so that Artifactory can trigger
  # the workflow through GitHub REST API.
  workflow_dispatch: 
    # inputs are optional, they may be used to convey contextual data
    # from the JFrog event to the workflow.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print artifact_path
        run: echo  "triggerd"
